/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarCodeIcon: typeof import('./src/components/icons/barCode-icon.vue')['default']
    CheckBoxIcon: typeof import('./src/components/icons/checkBox-icon.vue')['default']
    Currency: typeof import('./src/components/icons/currency.vue')['default']
    CurrencyIcon: typeof import('./src/components/icons/currency-icon.vue')['default']
    ElButto: typeof import('element-plus/es')['ElButto']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    'ElCol:': typeof import('element-plus/es')['ElCol:']
    ElConfig: typeof import('element-plus/es')['ElConfig']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormitem: typeof import('element-plus/es')['ElFormitem']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElItem: typeof import('element-plus/es')['ElItem']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExcelIcon: typeof import('./src/components/icons/excel-icon.vue')['default']
    FieldIcon: typeof import('./src/components/field-icon/index.vue')['default']
    FieldSetting: typeof import('./src/components/field-setting/index.vue')['default']
    MultiSelect: typeof import('./src/components/icons/multiSelect.vue')['default']
    MultiSelectIcon: typeof import('./src/components/icons/multiSelect-icon.vue')['default']
    NumberIcon: typeof import('./src/components/icons/number-icon.vue')['default']
    ProgressIcon: typeof import('./src/components/icons/progress-icon.vue')['default']
    RatingIcon: typeof import('./src/components/icons/rating-icon.vue')['default']
    SettingForm: typeof import('./src/components/setting-form/index.vue')['default']
    SingleSelectIcon: typeof import('./src/components/icons/singleSelect-icon.vue')['default']
    TextIcon: typeof import('./src/components/icons/text-icon.vue')['default']
    Upload: typeof import('./src/components/upload/index.vue')['default']
    UploadIcon: typeof import('./src/components/icons/upload-icon.vue')['default']
    UrlIcon: typeof import('./src/components/icons/url-icon.vue')['default']
  }
}
